# Generated by Django 5.1.7 on 2025-04-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_ciudad_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='imagen',
            field=models.URLField(default='https://via.placeholder.com/800x600'),
        ),
    ]
