# Generated by Django 5.1.7 on 2025-04-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='destino',
            new_name='ciudad_visitada',
        ),
    ]
